version: '3.9'

services:
  django:
    build:
      context: .
    volumes:
      - ../animegrok:/animegrok
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  db:
    container_name: animegrok_db
    image: postgres:15.3-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
  pgadmin:
    container_name: animegrok_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: sanemi.sh.2022@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  redis:
    image: redis:7.0.11-alpine
    hostname: redis
  worker:
    build: 
      context: .
    hostname: worker
    entrypoint: celery
    command: -A config.celery.app worker --loglevel=info
    volumes:
      - ../animegrok/config:/animegrok/config
    links:
      - redis
    depends_on:
      - redis
  flower:
    build: 
      context: .
    hostname: flower
    entrypoint: celery
    command: A config.celery.app flower
    volumes:
      - ../animegrok/config:/animegrok/config
    links:
      - redis
    depends_on:
      - redis
volumes:
  pg_data: