# Generated by Django 4.2 on 2023-06-19 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_articledetailview_alter_video_options_article_videos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recomendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recarticle',
            name='users',
        ),
        migrations.AddField(
            model_name='recarticle',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recarticle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_rec_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='recarticle',
            name='article',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_recs', to='articles.article', verbose_name='Аниме'),
        ),
    ]
