# Generated by Django 4.2 on 2023-05-30 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='subscription',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='subs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
