# Generated by Django 4.2 on 2023-05-31 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscription_user_subscription_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name_plural': 'Подписки на аниме'},
        ),
    ]
