# Generated by Django 4.2 on 2023-05-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Изображение')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('title_alt', models.CharField(max_length=150, verbose_name='Альтернативное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('author', models.CharField(blank=True, null=True, verbose_name='Автор')),
                ('type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип')),
                ('studio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Студия')),
                ('date_aired', models.DateField(verbose_name='Дата выхода в эфир')),
                ('activity', models.CharField(choices=[('Продолжается', 'Продолжается'), ('Завершён', 'Завершён')], default='Продолжается', verbose_name='Тип')),
                ('duration', models.CharField(max_length=3, verbose_name='Длительность')),
                ('quality', models.CharField(verbose_name='Качество')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('coutry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('link', models.SlugField(max_length=150, unique=True)),
                ('poster', models.ImageField(blank=True, upload_to='posters/', verbose_name='Постер')),
                ('season', models.CharField(blank=True, max_length=150, null=True, verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('link', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звезды рейтинга',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=5000, verbose_name='Сообщение')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Аниме')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.reviews', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='articles.article', verbose_name='Аниме')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ratingstar', verbose_name='звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='ArticleShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='article_shots/', verbose_name='Изображение')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Аниме')),
            ],
            options={
                'verbose_name': 'Кадр из аниме',
                'verbose_name_plural': 'Кадры из аниме',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='article',
            name='genres',
            field=models.ManyToManyField(blank=True, to='articles.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitles',
            field=models.ManyToManyField(blank=True, related_name='subs_workers', to='articles.actor', verbose_name='Работали над субтитрами'),
        ),
        migrations.AddField(
            model_name='article',
            name='timing',
            field=models.ManyToManyField(blank=True, related_name='timing_workers', to='articles.actor', verbose_name='Тайминг'),
        ),
        migrations.AddField(
            model_name='article',
            name='voicing',
            field=models.ManyToManyField(blank=True, related_name='article_voicer', to='articles.actor', verbose_name='Озвучивание'),
        ),
    ]
