# Generated by Django 4.2 on 2023-05-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
