# Generated by Django 4.2 on 2023-05-09 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_episodes', to='articles.article', verbose_name='Аниме'),
        ),
        migrations.AddField(
            model_name='rating',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='articles.article', verbose_name='Аниме'),
        ),
        migrations.AddField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.ratingstar', verbose_name='звезда'),
        ),
        migrations.AddField(
            model_name='articleshot',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Аниме'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='articles.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='article',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='article', to='articles.genre', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitles',
            field=models.ManyToManyField(blank=True, related_name='subs_workers', to='articles.actor', verbose_name='Работали над субтитрами'),
        ),
        migrations.AddField(
            model_name='article',
            name='timing',
            field=models.ManyToManyField(blank=True, related_name='timing_workers', to='articles.actor', verbose_name='Тайминг'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='viewers',
            field=models.ManyToManyField(to='articles.viewer', verbose_name='Просмотры'),
        ),
        migrations.AddField(
            model_name='article',
            name='voicing',
            field=models.ManyToManyField(blank=True, related_name='article_voicer', to='articles.actor', verbose_name='Озвучивание'),
        ),
    ]
