# Generated by Django 4.2 on 2023-05-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_reviews_review_alter_article_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='genres',
            field=models.ManyToManyField(blank=True, to='articles.genre', verbose_name='Жанры'),
        ),
    ]
