# Generated by Django 4.2 on 2023-05-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.CharField(default='XX', verbose_name='Общее количество серий'),
        ),
    ]
