# Generated by Django 4.2 on 2023-05-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='articles.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='article', to='articles.genre', verbose_name='Жанры'),
        ),
    ]
