# Generated by Django 4.2 on 2023-05-18 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_options_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='viewed_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата просмотра'),
            preserve_default=False,
        ),
    ]
