# Generated by Django 4.2 on 2023-05-29 07:05

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='articles.review', verbose_name='Родительский комментарий'),
        ),
    ]
