# Generated by Django 4.2 on 2023-05-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_actor_options_alter_viewer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='on_main',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной'),
        ),
    ]
