# Generated by Django 4.2 on 2023-05-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_actor_description_en_actor_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ru',
        ),
    ]
