# Generated by Django 4.2 on 2023-05-31 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_article_title_en_remove_article_title_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='user_en',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='user_ru',
        ),
    ]
