# Generated by Django 4.2 on 2023-05-31 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_actor_user_en_remove_actor_user_ru'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('episode',), 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='article',
            name='activity_en',
            field=models.CharField(choices=[('Продолжается', 'Продолжается'), ('Завершён', 'Завершён')], default='Продолжается', null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='article',
            name='activity_ru',
            field=models.CharField(choices=[('Продолжается', 'Продолжается'), ('Завершён', 'Завершён')], default='Продолжается', null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_en',
            field=models.CharField(blank=True, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_ru',
            field=models.CharField(blank=True, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='duration_en',
            field=models.CharField(max_length=3, null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='article',
            name='duration_ru',
            field=models.CharField(max_length=3, null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='article',
            name='studio_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Студия'),
        ),
        migrations.AddField(
            model_name='article',
            name='studio_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Студия'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='article',
            name='type_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='article',
            name='type_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='articleshot',
            name='article_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Аниме'),
        ),
        migrations.AddField(
            model_name='articleshot',
            name='article_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Аниме'),
        ),
        migrations.AddField(
            model_name='articleshot',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='articleshot',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='articleshot',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='articleshot',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='video',
            name='article_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_episodes', to='articles.article', verbose_name='Аниме'),
        ),
        migrations.AddField(
            model_name='video',
            name='article_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_episodes', to='articles.article', verbose_name='Аниме'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название эпизода'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название эпизода'),
        ),
    ]
