# Generated by Django 4.2 on 2023-06-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_article_activity_alter_article_activity_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleshot',
            name='article_en',
        ),
        migrations.RemoveField(
            model_name='articleshot',
            name='article_ru',
        ),
        migrations.RemoveField(
            model_name='video',
            name='article_en',
        ),
        migrations.RemoveField(
            model_name='video',
            name='article_ru',
        ),
    ]
