# Generated by Django 4.2 on 2023-06-02 15:13

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.detail
import src.base.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_remove_articleshot_article_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetailView',
            fields=[
                ('genre_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.genre')),
            ],
            bases=(django.views.generic.detail.DetailView, src.base.mixins.CountViewerMixin, 'articles.genre'),
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-create_at',), 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='article',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='art_episodes', to='articles.video', verbose_name='Эпизоды'),
        ),
    ]
