# Generated by Django 4.2 on 2023-05-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='status',
            field=models.CharField(choices=[('admin', 'Администратор'), ('voicer', 'Озвучка'), ('timer', 'Тайминг'), ('subtitles', 'Переводчик'), ('user', 'Пользователь')], default='user', help_text='Выберите статус пользователя', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='usernet',
            name='gender',
            field=models.CharField(choices=[('М', 'male'), ('Ж', 'female')], default='male', max_length=6, verbose_name='Пол'),
        ),
    ]
