# Generated by Django 4.2 on 2023-05-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_user'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernet',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='users', to='articles.article', verbose_name='Подписки'),
        ),
    ]
